.github/ISSUE_TEMPLATE.md

fix: Minor typos in the issue template

---

.github/ISSUE_TEMPLATE.md

fix: Add applicable repos and remove status from the issues template

---

Architecture/multiple-ovms-json-config.md

feat: design for multiple ovms server json config files

---

Architecture/target-device.md

Changing the platform parameter will break existing testing scripts. Scripts and testing will need to be updated to the target_device.
#5

feat: Replace platform parameter with the target_device parameter

---

performance-tools/benchmark.md

docs: Add benchmarking documentation

---

.github/workflows/github-pages.yml

docs: Create GitHub pages action

---

docs_src/performance-tools/benchmark.md

docs: add documentation for benchmarking stream density

---

docs_src/use-cases/AiCSD/aicsd.md
docs_src/use-cases/AiCSD/pipeline-grpc-go.md
docs_src/use-cases/use-cases.md
mkdocs.yml

#**issue_number**
This PR works in conjunction with the AiCSD feature for the service `as-pipeline-grpc-go`

docs: Add docs for grpc-go service

---

docs_src/troubleshooting.md
mkdocs.yml

Adding a troubleshooting guide to the general documentation
#**issue_number**
automated-self-checkout
retail-use-cases

doc: Add troublshooting section

---

Makefile
docs_src/use-cases/loss-prevention/advanced.md

Docs: Adding class filtering section

---

.github/workflows/github-pages.yml

deploy github pages manually

---

.github/workflows/github-pages.yml

Adding github pages dependencies

---

docs_src/performance-tools/benchmark.md

feat: update benchmarking docs with new parsing feature

---

docs_src/performance-tools/benchmark.md
docs_src/use-cases/automated-self-checkout/performance.md

docs: update performance tools documentation

---

docs_src/use-cases/automated-self-checkout/advanced.md
docs_src/use-cases/automated-self-checkout/getting_started.md
docs_src/use-cases/automated-self-checkout/performance.md

docs: Automated Self-Checkout improvements

---

docs/workshops.html
docs_src/workshops.md
workshops/README.md

doc: fix hyperlinks

---

docs_src/use-cases/automated-self-checkout/advanced.md
docs_src/use-cases/automated-self-checkout/performance.md

docs: PR review comments

---

.github/workflows/github-pages.yml
docs_src/workshops.md

Ghpages fix

---

.github/workflows/github-pages.yml
docs_src/workshops.md

Ghdeploy fix

---

docs_src/use-cases/automated-self-checkout/advanced.md

#**[issue_number](https://github.com/intel-retail/automated-self-checkout/issues/753)**

Added the documentation for using a custom model

---

docs_src/use-cases/loss-prevention/architecture.md

LP Architecture

---

mkdocs.yml

Fix mermaid rendering issue

---

docs_src/use-cases/automated-self-checkout/advanced.md
docs_src/use-cases/automated-self-checkout/performance.md
docs_src/use-cases/loss-prevention/advanced.md
docs_src/use-cases/loss-prevention/getting_started.md

1. Added `benchmark-quickstart` command guide.
2. Added lists of envs that can be used to change the command as required.
3. Description of the pipelines 
#**issue_number**

ASC age prediction and performance update.md

---

docs_src/use-cases/automated-self-checkout/performance.md
docs_src/use-cases/loss-prevention/advanced.md
docs_src/use-cases/loss-prevention/getting_started.md
docs_src/use-cases/order-accuracy/advanced.md
docs_src/use-cases/order-accuracy/getting_started.md

1. `benchmark-quickstart` command instructions updated.
2. OOM flag instructions updated.
3. Stream density command updated.
4. "Automated Self-Checkout" term correction.
#**issue_number**

OA- benchmark-quickstart and OOM updates.
